package com.foldit.utilites.negotiationconfigholder.constant;

public interface NegotiationConstant {

    String GOOGLE_API_KEY_FOR_DISTANCE_MATRIX = "GOOGLE_API_KEY_FOR_DISTANCE_MATRIX";
    String DEFAULT_STORE_ID = "DEFAULT_STORE_ID";
    String OLD_TIME_SLOTS_BATCH_SIZE_IN_HOUR_DIFFERENCE = "OLD_TIME_SLOTS_BATCH_SIZE_IN_HOUR_DIFFERENCE";
    String NEW_TIME_SLOTS_BATCH_SIZE_IN_HOUR_DIFFERENCE = "NEW_TIME_SLOTS_BATCH_SIZE_IN_HOUR_DIFFERENCE";
    String TIME_SLOTS_QUANTITY_TO_SHOW = "TIME_SLOTS_QUANTITY_TO_SHOW";
    String LAST_DATE_TO_SHOW_OLD_SLOTS_TIMINGS= "LAST_DATE_TO_SHOW_OLD_SLOTS_TIMINGS";

}
